    <style>
        .botao-verde {
            background-color: #e90602;
            color: rgb(7, 6, 6);
            padding: 12px 20px;
            border-radius: 30px;
            border: none;
            cursor: pointer;
            font-weight: bold;
            margin: 10px;
        }
        .botao-kawaii {
            background-color: #ff0026;
            color: rgb(12, 12, 12);
            padding: 12px 20px;
            border-radius: 30px;
            border: none;
            cursor: pointer;
            font-weight: bold;
            margin: 10px;
        }
    </style>